import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../globals.css";
import MainNavbar from "#/components/nav";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={
          inter.className + " dark h-full min-h-[100vh] overflow-scroll"
        }
      >
        <MainNavbar />
        <main className="w-full flex justify-center">
          <div className="w-full max-w-screen-lg px-4">{children}</div>
        </main>
      </body>
    </html>
  );
}
